// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    IconAdd: typeof import('./src/components/icons/IconAdd.vue')['default']
    IconArrowBottom: typeof import('./src/components/icons/IconArrowBottom.vue')['default']
    IconArrowTop: typeof import('./src/components/icons/IconArrowTop.vue')['default']
    IconBatchDel: typeof import('./src/components/icons/IconBatchDel.vue')['default']
    IconCamera: typeof import('./src/components/icons/IconCamera.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDelete: typeof import('./src/components/icons/IconDelete.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconEditPen: typeof import('./src/components/icons/IconEditPen.vue')['default']
    IconExport: typeof import('./src/components/icons/IconExport.vue')['default']
    IconMenuCollapse: typeof import('./src/components/icons/IconMenuCollapse.vue')['default']
    IconMenuDataPanel: typeof import('./src/components/icons/IconMenuDataPanel.vue')['default']
    IconMenuElevator: typeof import('./src/components/icons/IconMenuElevator.vue')['default']
    IconMenuOperateNotice: typeof import('./src/components/icons/IconMenuOperateNotice.vue')['default']
    IconMenuRealtime: typeof import('./src/components/icons/IconMenuRealtime.vue')['default']
    IconMenuSystemSettings: typeof import('./src/components/icons/IconMenuSystemSettings.vue')['default']
    IconMenuWorkCenter: typeof import('./src/components/icons/IconMenuWorkCenter.vue')['default']
    IconMenuWorkSetting: typeof import('./src/components/icons/IconMenuWorkSetting.vue')['default']
    IconMessageNotice: typeof import('./src/components/icons/IconMessageNotice.vue')['default']
    IconPlus: typeof import('./src/components/icons/IconPlus.vue')['default']
    IconSearch: typeof import('./src/components/icons/IconSearch.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IconWarningFilled: typeof import('./src/components/icons/IconWarningFilled.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/svg-icon/SvgIcon.vue')['default']
  }
}
