name: push to gh-pages

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.18.0'

    - name: Install dependencies
      run: npm install -g pnpm && pnpm install

    - name: Build
      run: npm run build:gh-pages

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
        publish_dir: ./dist
